### ISSUE TITLE
Flow diagram of game

### ISSUE THREAD

**Issue by srohilla** [srohilla/CodeSpanners#1]

**Comment by virajnilakh** [comment]
![img-20160918-wa0006](https://cloud.githubusercontent.com/assets/19594983/18619576/b33fb2d6-7e1d-11e6-9be7-1936d2f5853f.jpg)

**Comment by virajnilakh** [comment]
![img-20160918-wa0006](https://cloud.githubusercontent.com/assets/19594983/18619969/79eb09f0-7e26-11e6-8c07-661b833e1622.jpg)
