### ISSUE TITLE
Use case Diagram

### ISSUE THREAD

**Issue by srohilla** [srohilla/CodeSpanners#4]

**Comment by virajnilakh** [comment]
![classproject](https://cloud.githubusercontent.com/assets/19594983/18933347/36c583a2-8589-11e6-877c-da9406ea7fad.PNG)

**Comment by amaydubey** [comment]
0 level Use case diagram:
![usecase diagram0](https://cloud.githubusercontent.com/assets/6437583/19010431/b80d46b4-8734-11e6-8cb4-61ef0cb86205.png)
