### ISSUE TITLE
Conceptualization of activity

### ISSUE THREAD

**Issue by srohilla** [srohilla/CodeSpanners#5]

**Comment by n3o-Bhushan** [comment]
[Conceptualization of activity  .docx](https://github.com/srohilla/CodeSpanners/files/479066/Conceptualization.of.activity.docx)

**Comment by n3o-Bhushan** [comment]
Created conceptualization of activity document.

**Comment by n3o-Bhushan** [comment]
[Conceptualization of activity  .docx](https://github.com/srohilla/CodeSpanners/files/479068/Conceptualization.of.activity.docx)

**Comment by n3o-Bhushan** [comment]
Created conceptualization of activity document.
