### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by srohilla** [srohilla/CodeSpanners#7]

**Comment by virajnilakh** [comment]
![classdiagram](https://cloud.githubusercontent.com/assets/19594983/18773337/0ae1cc4e-8103-11e6-8b18-30670e3e3379.PNG)

**Comment by virajnilakh** [comment]
![classdiagram](https://cloud.githubusercontent.com/assets/19594983/18774659/47effe78-8110-11e6-8b5f-188330a9ab56.PNG)
